# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/fasthtml_todo",
        "doc_host": "https://rnair98.github.io",
        "git_url": "https://github.com/rnair98/fasthtml_todo",
        "lib_path": "fasthtml_todo",
    },
    "syms": {
        "fasthtml_todo.core": {
            "fasthtml_todo.core.foo": ("core.html#foo", "fasthtml_todo/core.py")
        }
    },
}
